language: node_js
node_js:
- '8'
cache: node_modules
jobs:
  include:
  - stage: build
    install:
    - npm install --no-optional
    - npm dedupe
    script: true
  - stage: deploy
    if: tag IS present
    install: true
    script: vsce publish -p ${personal-access-token}
env:
  global:
    secure: AjgVd/y6PL4YkDEF/ksMKSJAbJ4lwOggifhqiP057GRj0yDufK9GTkSvCcHqoHDugeto4jFSy1GRG61WPoY+rz9h7b7LqOoiaiViLuIJRBDCC8BEVb6veoK2M3ewk1Svs5oSYsQW95ErTDeTZaPhEVNTUIfT/mpqhGNVG0XlmUkYckGlY86sYnXARHWjaMhS3Mk6uEM7P/yivzAF6ofr+yTnCn+hW1bE60mndGdmDdThREzR9KOd4IJijgAWy8Ad4PLayTk6mn0yvV9Cvq2cXXOH1Ur/0DiDA0qNrKSMPRZnvaxIUneOQY7myL7MgLGcTU4W7hmX+R4+a7yB1wOl0pRUHbVVgLBKhycSm6Q1UafEEMN7Qqj6MLTlXbxt11X8PyKvuSBc/muT2RAomih20feHALi1OY9QX3jOgUPeBXBjLSzPkp6mbir9pPRWD7wCMC3mab/uGV0eX1MYKyVVKpfL6wh6lYnwedKXF77B1GvDlehKaBU2DtRk5iXgOnKMIWSNZEznpLCmYqYlIca+P9ahzi8Vfxt918gMDhkKi8B8hSGDJgabk5DxFkvtpR46JxMAPvAldugWpb5VUPruTX8aOKHOjO9ygbnNdjMuqHEhEufkEpwBvxr0tnOaIYs2An34KWUuTjRInvCvTDndZki9IlyHuWbkXGsbtAaL80o=
