language: node_js

jobs:
  include:
    - stage: install
      before_script:
        - npm install
    - stage: deploy
      if: tag IS present
      before_install:
        - npm install -g vsce
      script: vsce publish -p ${personal-access-token} 

  
