language: node_js
node_js:
  - "8"
jobs:
  include:
    - stage: install
      before_script:
        - npm install
      script:
        - npm test --silent
    - stage: deploy
      if: tag IS present
      before_install:
        - npm install -g vsce
      script: vsce publish -p ${personal-access-token} 

  
