language: node_js
node_js:
- '8'
cache: node_modules
jobs:
  include:
  - stage: build
    install:
    - npm install --no-optional
    - npm dedupe
    script: true
  - stage: deploy
    if: tag IS present
    install:
    - npm install --no-optional
    - npm dedupe
    script: vsce publish -p ${personal-access-token}
env:
  global:
  - secure: VAJmqr9UE7pdUQKZ+KCc7zrWS0JW9BAs1flmr+O5vGnYIcgdTk1V5ZK5uyHFcjkOSh3vuyHN1aXRABBcTj2nJN8/Ud9jtqcdd5TheaDnmtj2glsE4Vzyzz9cVW3mOpIivIRGTMwt2Itx+TedvwVBedUE5iPK9cF9IWAdPUbHG8RndgrSXx9j4SyIgTZqZNXC/vCO62ph8QTpscTsAwjham/ENF4DE9k0TLmAdsoCaLcVJJe2HW6QOOkLZCF9DNUp8/fF2ClXtbV90zJHOQuvRN3Tg22FenIlcHXWiitkmi45PslSsRgXvyGSTyRPR4zjEHtkP0k8zLPoAQ9g7hi8YO655bbzGEcecpuGNH/eYvHFfXIASwwQ7GXz2FNsVeeQtRjw3sQAEp3BxvyxhSz4pDO4uk7TpX0pf5yZhhCLt+y2XnGOKJxGV0tJXXA06tZpj0aQZeNCEahQpCpHMSQcoo7mXzCkzIi9MANSkdbFO88vuVXDLL9TcaI+IJi63yuVpfVZHXKXr6aG/6EOgnHTftViAWUF/+TsXPov9eYnJRnzfczPVZSSwtt223NfECNjQ1d77iw7nPx7VhpkteWrvRx4vCIJkC1aEDBYDYWr62NLd4jctNGgAtitD+iI2vCElQurXnUCo4XuvDeojaPwGxUWNT+QHmrm4+iQM8IVPpc=
