language: node_js
node_js:
- '8'
cache: node_modules
jobs:
  include:
  - stage: build
    install:
    - npm install --no-optional
    - npm dedupe
    script: true
  - stage: deploy
    if: tag IS present
    install:
    - npm install --no-optional
    - npm dedupe
    script: vsce publish -p ${personal-access-token}
env:
  global:
  - secure: ghDCNfykJWdf2AlNz+XRQKGzpJAFFYEEAA8wZahvsUtPSvjUJb88lrcjnwKpujknPy+8ESa2yBb545ZNMUx0oKb/6vzGIP6n18g6m+iCvSbeyBSTsugDIA4Cgjw8k8ffenZrGVNQ09TSi96NwlkpS3enhPJSFfFg+/B1Wt8KeNnXk3aZB7IjHrBqwa5f9kl5qiifbBrCRxE9ACSlJ7ZmjTvmBMgkH43uI4vK7oFKBP+i4qhct549vY42MVUrYC/jzy3r9CAMpbAGcsO7JAirLZcO5M52QYnb7pTZtbaoFp10ivUV85Nf/TWVizhadNs4VeZnsYS1iAHbt+iNgl/xLivskyXcDPmB6xmWDbJTmRNvOdFQ2r+MqWb5UnQ8fVLZIguNHiMNlmuG6eEppzjdfg40YA7w7L6TsDe6j56JXyxudIz93EGnoqkYckVW+tgbaOQGM0/QJzkP5WDraOyHKEBgwYIowWAdVjJiv5AHrmuppoLYEwtFOWu0Z9NbZdlWbiiHiGcFeig0IIDR4UspXZqabLmGDJ4moY5yNQqdGSAt2/H4E+1aGCZnP5qLgF0gXwRmMS2NyZo96rciESBxq4xcAzKVQ7nlWDSpzeFPf8YAy1ge0Oqs6p8kcT4bUOa0nTkldY94bm57veMx6zd4Rwuv/dqxmxGV/Su4vIJNUxs=
